# Generated by Django 3.2.3 on 2021-06-03 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_url_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default='', upload_to='news/static/images/', verbose_name='Картинка на главную'),
            preserve_default=False,
        ),
    ]
