# Generated by Django 3.2.3 on 2021-06-03 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_article_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'get_latest_by': 'datetime', 'ordering': ['-datetime']},
        ),
    ]
