# Generated by Django 3.2.3 on 2021-06-18 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_modelbranch'),
        ('dealers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='city_slug',
            field=models.SlugField(default='', verbose_name='url города'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dealer',
            name='address',
            field=models.CharField(max_length=50, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.brand', verbose_name='Марка'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='city',
            field=models.CharField(max_length=50, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='company_name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='coordinates',
            field=models.CharField(max_length=50, verbose_name='Координаты в Яндекс.Картах'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='url',
            field=models.URLField(verbose_name='Сайт'),
        ),
    ]
