# Generated by Django 3.2.3 on 2021-05-29 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='brand_url',
            field=models.URLField(default='', max_length=50),
        ),
    ]
