# Generated by Django 3.2.3 on 2021-06-01 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_brand_brand_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='tag',
            field=models.CharField(default='', max_length=20),
        ),
    ]
