# Generated by Django 3.2.3 on 2021-06-02 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20210602_1930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='tag',
            new_name='slug',
        ),
    ]
